### PR TITLE
Updates to PDs

### PR DESCRIPTION
**Pull request by friedrichknuth**
Updates to PD data levels, units and precision

---
This change is [Reviewable](https://reviewable.io/reviews/oceanobservatories/preload-database/8)

### CODE REVIEW

**Comment by danmergens** [comment]
PD359 - thermistor_raw is in counts from the sensor, not Volts

**Comment by friedrichknuth** [comment]
Issues with PD359/PD938 and PD539-541 should be resolved with the latest commits.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/oceanobservatories/preload-database/8#-:-KYU04C1m-Bcx3QwPjyd:b-hm6hsu)*

**Comment by friedrichknuth** [comment]
Is this good to go?

**Comment by petercable** [comment]
All changes merged in other PRs.

**Pull request closed without merging**
