### PR TITLE
Updates to multiple PD numbers

### PR DESCRIPTION
**Pull request by friedrichknuth**
Descriptions, Display Names, Data Product Identifiers and Standard Names

---
This change is [Reviewable](https://reviewable.io/reviews/oceanobservatories/preload-database/3)

### CODE REVIEW

**Comment by petercable** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[csv/ParameterDefs.csv, line 3376 at r3](https://reviewable.io:443/reviews/oceanobservatories/preload-database/3#-KX85p3thKWtVIo516--:-KX85p3thKWtVIo516-0:b6rh07e) ([raw file](https://github.com/oceanobservatories/preload-database/blob/6954a1b3e41fdf03656affac2e4b105fc22d9dea/csv/ParameterDefs.csv#L3376)):*
> ```CSV
> CTDBP_NO,CTDBP-NO,ctdbp_no_practical_salinity,PD3649,ctdbp_no_practical_salinity_function_float32_1,0,function,,float32,,1,-9999999,Practical Salinity,4,,PFID26,"{""c"":""PD3648"",""t"":""PD908"",""p"":""PD3647""}",,PRACSAL,sea_water_practical_salinity,PRACSAL_L2,,Salinity is generally defined as the concentration of dissolved salt in a parcel of seawater. Practical Salinity is a more specific unitless quantity calculated from the conductivity of seawater and adjusted for temperature and pressure. It is approximately equivalent to Absolute Salinity (the mass fraction of dissolved salt in seawater) but they are not interchangeable. Units: unitless,Ready for review,,Seawater Practical Salinity,,Science Data,L2
> CTDBP_NO,CTDBP-NO,ctdbp_no_seawater_density,PD3650,ctdbp_no_seawater_density_function_float32_kg_m_3,0,function,,float32,,kg m-3,-9999999,Seawater Density,4,,PFID27,"{""SP"":""PD3649"",""t"":""PD908"",""p"":""PD3647"",""lat"":""CC_lat"",""lon"":""CC_lon""}",,DENSITY,sea_water_density,DENSITY_L2,,"Seawater density is defined as mass per unit volume and is calculated using the temperature, salinity, and pressure of a seawater sample. Units: kg m-3",Ready for review,,Seawater Density,,Science Data,L2
> <<<<<<< HEAD
> ```

These two lines require merging... The changes from <<<<<<<< HEAD to ======= are yours and from ======= to >>>>>>> oceanobservatories/master were changed by someone else.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/oceanobservatories/preload-database/3)*

**Comment by petercable** [comment]
*[csv/ParameterDefs.csv, line 2002 at r3](https://reviewable.io:443/reviews/oceanobservatories/preload-database/3#-KX89ZoqavYMHrnO7Ioa:-KX89ZoqavYMHrnO7Iob:bon6wpo) ([raw file](https://github.com/oceanobservatories/preload-database/blob/6954a1b3e41fdf03656affac2e4b105fc22d9dea/csv/ParameterDefs.csv#L2002)):*
> THSPH_A,THSPH,thsph_s2electrode,PD2263,thsph_s2electrode_quantity_int16_counts,0,quantity,,int16,,counts,-9999,Hydrogen Sulfide Measurement,,,,,,,,THSPHHS-H2S_L0,,"Sulfide Electrode measurement at the high temperature location. Units: counts,,,,,Unprocessed Data,L0

You added a " at the beginning of the string "Sulfide Electrode measurement at the high... Units: counts", but are missing the " at the end.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/oceanobservatories/preload-database/3)*

**Comment by friedrichknuth** [comment]
*[csv/ParameterDefs.csv, line 3376 at r3](https://reviewable.io:443/reviews/oceanobservatories/preload-database/3#-KX85p3thKWtVIo516--:-KXBVt4M_cl15fgchEH7:btxkgz4) ([raw file](https://github.com/oceanobservatories/preload-database/blob/6954a1b3e41fdf03656affac2e4b105fc22d9dea/csv/ParameterDefs.csv#L3376)):*
<details><summary><i>Previously, petercable (Pete Cable) wrote…</i></summary>
> These two lines require merging... The changes from <<<<<<<< HEAD to ======= are yours and from ======= to >>>>>>> oceanobservatories/master were changed by someone else.
</details>
This is odd since I did not manually touch this PD number when editing the file. It seems quotation marks were removed by someone else. Possibly a script?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/oceanobservatories/preload-database/3)*

**Comment by friedrichknuth** [comment]
*[csv/ParameterDefs.csv, line 2002 at r3](https://reviewable.io:443/reviews/oceanobservatories/preload-database/3#-KX89ZoqavYMHrnO7Ioa:-KXCcIM9YZQqXYUd-Usa:b-yuhefl) ([raw file](https://github.com/oceanobservatories/preload-database/blob/6954a1b3e41fdf03656affac2e4b105fc22d9dea/csv/ParameterDefs.csv#L2002)):*
<details><summary><i>Previously, petercable (Pete Cable) wrote…</i></summary>
> > THSPH_A,THSPH,thsph_s2electrode,PD2263,thsph_s2electrode_quantity_int16_counts,0,quantity,,int16,,counts,-9999,Hydrogen Sulfide Measurement,,,,,,,,THSPHHS-H2S_L0,,"Sulfide Electrode measurement at the high temperature location. Units: counts,,,,,Unprocessed Data,L0
> 
> You added a " at the beginning of the string "Sulfide Electrode measurement at the high... Units: counts", but are missing the " at the end.
</details>
I submitted a new commit to this pull request with the " added.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/oceanobservatories/preload-database/3)*

**Pull request closed without merging**
