### PR TITLE
Removed non-compliant names from the standard names column

### PR DESCRIPTION
**Pull request by najascutellatus**
Removed non-compliant names from the standard names column as per
redmine ticket #11300

---
This change is [Reviewable](https://reviewable.io/reviews/oceanobservatories/preload-database/9)

### CODE REVIEW

**Comment by najascutellatus** [comment]
Damn excel! I only changed about 15 things (removing improper standard names). Let me know if you'd like me to redo this so we can actually see the diff.

**Comment by petercable** [comment]
It looks like excel did two things.

- Changed line endings
- Change file encoding

The first one is easy enough to fix, but I'm not sure about the second. When I view the changes here I see things like this:

BEFORE: compass heading (0.1°)
AFTER: compass heading (0.1<E5><A1>)

**Comment by najascutellatus** [comment]
:lgtm: Can you check this again?

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/oceanobservatories/preload-database/9#-:-KbzwZyZqJw07s8BZKjp:b44vkqx)*

**Comment by petercable** [comment]
I still see dos line endings and strange characters with your latest. If you click the "View changes" button associated with your last commit it only shows one line changed.

**Pull request closed without merging**
