### PR TITLE
Issue 13114 - correct 'Stream Content' for flort_sample

### PR DESCRIPTION
**Pull request by danmergens**
Change-Id: Icc07990c390a3a76399e81083b512b35c76648b0

### CODE REVIEW

**Comment by tlfish3638** [comment]
Dan,

Is 13114 going into sprint 12?

Tim Fisher
Sr. Software Engineer I
OOI Omaha Engineering
Software 3 DV
IIS Engineering and Technology
Raytheon Company

+1 4023908017   (office, OOI)
+1 4023908960   (office, alternate)
Timothy.L.Fisher@raytheon.com<mailto:Timothy.L.Fisher@raytheon.com>

2120 South 72nd St, 8th Floor
Omaha, NE 68124 USA
www.raytheon.com<http://www.raytheon.com/>

Follow Raytheon On
[cid:image001.png@01D3939C.7D9E6470]<http://twitter.com/raytheon> [cid:image002.png@01D3939C.7D9E6470] <http://www.youtube.com/user/raytheoncompany>  [cid:image003.png@01D3939C.7D9E6470] <http://www.facebook.com/Raytheon>  [cid:image004.png@01D3939C.7D9E6470] <http://www.linkedin.com/companies/raytheon>

[cid:image005.png@01D3939C.7D9E6470]

This message contains information that may be confidential and privileged. Unless you are the addressee (or authorized to receive mail for the addressee), you should not use, copy or disclose to anyone this message or any information contained in this message. If you have received this message in error, please so advise the sender by reply e-mail and delete this message. Thank you for your cooperation.

**Comment by danmergens** [comment]
I figured we were too late for Sprint 12, but if you have time, squash with the previous release (if any) and update `RELEASE_NOTES.md`.

**Comment by tlfish3638** [comment]
Never mind. I was thinking about needing to update the RELEASE_NOTES file for the end of sprint 12 but I remembered that’s not necessary now.

But to be sure, when I run “python load_preload.py …” I’m thinking it’s critical I do a “git checkout” on the final sprint 12 commit beforehand.

Tim Fisher
Sr. Software Engineer I
OOI Omaha Engineering
Software 3 DV
IIS Engineering and Technology
Raytheon Company

+1 4023908017   (office, OOI)
+1 4023908960   (office, alternate)
Timothy.L.Fisher@raytheon.com<mailto:Timothy.L.Fisher@raytheon.com>

2120 South 72nd St, 8th Floor
Omaha, NE 68124 USA
www.raytheon.com<http://www.raytheon.com/>

Follow Raytheon On
[cid:image001.png@01D393A2.B53AF000]<http://twitter.com/raytheon> [cid:image002.png@01D393A2.B53AF000] <http://www.youtube.com/user/raytheoncompany>  [cid:image003.png@01D393A2.B53AF000] <http://www.facebook.com/Raytheon>  [cid:image004.png@01D393A2.B53AF000] <http://www.linkedin.com/companies/raytheon>

[cid:image005.png@01D393A2.B53AF000]

This message contains information that may be confidential and privileged. Unless you are the addressee (or authorized to receive mail for the addressee), you should not use, copy or disclose to anyone this message or any information contained in this message. If you have received this message in error, please so advise the sender by reply e-mail and delete this message. Thank you for your cooperation.

**Comment by danmergens** [comment]
If you reply on github instead of replying via email, we won't get you entire message content in the conversation. You're correct about the instructions for JJ. Point him to the correct commit version (or the tag is better) that we want him to use for the release.

**Pull request merged**
