### PR TITLE
revised commit #37

### PR DESCRIPTION
**Pull request by leilabbb**
completed “streamtype” & “streamcontent “ columns

### CODE REVIEW

**Comment by leilabbb** [comment]
Dan, not sure why I am getting a file conflict error, since my local version of the file I have started working with is the same as the one on the GitHub repo. Were there any recent changes made to the list of "parametersids" that I am not seeing ? I think I will need help resolving the conflict in the file.

**Comment by danmergens** [comment]
I tried the "Resolve conflicts" button above, but it didn't look like an easy fix here with the GitHub web tools. I recommend you look at the following article for how to resolve merge conflicts: https://stackoverflow.com/questions/161813/how-to-resolve-merge-conflicts-in-git

What editor are you using to make updates? If you are using one that automatically changes line endings, that can wreak havoc on diff tools. 

If you're still having problems after trying to amend this pull request, I can fix it, but it will take some time.

**Comment by leilabbb** [comment]
Hi Dan,

I use MacVim to edit the preload sheets.

I am travelling to Paris this afternoon and I won’t be back until Friday. So, will look at the info you sent when I am back.

Thanks.
Leila

--
Leila Belabbassi PhD, Oceanographer
Associated Data Manager for OOI Program
Department of Marine and Coastal Sciences
Rutgers, The State University of New Jersey
New Brunswick, NJ 08901-8524
Office Tel: (848)932-3260
Cellphone:  (713)962-9834

**Comment by leilabbb** [comment]
closing this pull request. it has been a while since I have worked on this and now it is more confusing then ever. Starting over.

**Pull request closed without merging**
